# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/ui/qtsixa_newdevw.ui'
#
# Created: Sat Apr  2 22:18:55 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewDevW(object):
    def setupUi(self, NewDevW):
        NewDevW.setObjectName(_fromUtf8("NewDevW"))
        NewDevW.resize(604, 483)
        NewDevW.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wizardPage1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.wizardPage1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.wizardPage1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.co_dev = QtGui.QComboBox(self.wizardPage1)
        self.co_dev.setObjectName(_fromUtf8("co_dev"))
        self.co_dev.addItem(_fromUtf8(""))
        self.co_dev.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.co_dev)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        NewDevW.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wizardPage2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ch_led = QtGui.QCheckBox(self.wizardPage2)
        self.ch_led.setChecked(True)
        self.ch_led.setObjectName(_fromUtf8("ch_led"))
        self.verticalLayout_2.addWidget(self.ch_led)
        self.ch_js = QtGui.QCheckBox(self.wizardPage2)
        self.ch_js.setChecked(True)
        self.ch_js.setObjectName(_fromUtf8("ch_js"))
        self.verticalLayout_2.addWidget(self.ch_js)
        self.ch_input = QtGui.QCheckBox(self.wizardPage2)
        self.ch_input.setObjectName(_fromUtf8("ch_input"))
        self.verticalLayout_2.addWidget(self.ch_input)
        self.ch_rumble = QtGui.QCheckBox(self.wizardPage2)
        self.ch_rumble.setChecked(True)
        self.ch_rumble.setObjectName(_fromUtf8("ch_rumble"))
        self.verticalLayout_2.addWidget(self.ch_rumble)
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.r_auto_led = QtGui.QRadioButton(self.groupBox_3)
        self.r_auto_led.setChecked(True)
        self.r_auto_led.setObjectName(_fromUtf8("r_auto_led"))
        self.gridLayout_2.addWidget(self.r_auto_led, 0, 0, 1, 1)
        self.ch_led_anim = QtGui.QCheckBox(self.groupBox_3)
        self.ch_led_anim.setChecked(True)
        self.ch_led_anim.setObjectName(_fromUtf8("ch_led_anim"))
        self.gridLayout_2.addWidget(self.ch_led_anim, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.r_manual_led = QtGui.QRadioButton(self.groupBox_3)
        self.r_manual_led.setObjectName(_fromUtf8("r_manual_led"))
        self.horizontalLayout_2.addWidget(self.r_manual_led)
        self.r_led_n = QtGui.QSpinBox(self.groupBox_3)
        self.r_led_n.setEnabled(False)
        self.r_led_n.setMinimum(1)
        self.r_led_n.setMaximum(10)
        self.r_led_n.setObjectName(_fromUtf8("r_led_n"))
        self.horizontalLayout_2.addWidget(self.r_led_n)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.r_rumble_new = QtGui.QRadioButton(self.groupBox)
        self.r_rumble_new.setChecked(True)
        self.r_rumble_new.setObjectName(_fromUtf8("r_rumble_new"))
        self.gridLayout.addWidget(self.r_rumble_new, 0, 0, 1, 1)
        self.r_rumble_old = QtGui.QRadioButton(self.groupBox)
        self.r_rumble_old.setObjectName(_fromUtf8("r_rumble_old"))
        self.gridLayout.addWidget(self.r_rumble_old, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem3 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ch_timeout = QtGui.QCheckBox(self.wizardPage2)
        self.ch_timeout.setEnabled(True)
        self.ch_timeout.setObjectName(_fromUtf8("ch_timeout"))
        self.horizontalLayout_4.addWidget(self.ch_timeout)
        self.r_timeout = QtGui.QSpinBox(self.wizardPage2)
        self.r_timeout.setEnabled(False)
        self.r_timeout.setMinimum(5)
        self.r_timeout.setMaximum(9999)
        self.r_timeout.setProperty("value", 30)
        self.r_timeout.setObjectName(_fromUtf8("r_timeout"))
        self.horizontalLayout_4.addWidget(self.r_timeout)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(20, 109, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        NewDevW.addPage(self.wizardPage2)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wizardPage)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.js_button = QtGui.QCheckBox(self.wizardPage)
        self.js_button.setChecked(True)
        self.js_button.setObjectName(_fromUtf8("js_button"))
        self.verticalLayout_4.addWidget(self.js_button)
        self.js_sbutton = QtGui.QCheckBox(self.wizardPage)
        self.js_sbutton.setChecked(True)
        self.js_sbutton.setObjectName(_fromUtf8("js_sbutton"))
        self.verticalLayout_4.addWidget(self.js_sbutton)
        self.js_axis = QtGui.QCheckBox(self.wizardPage)
        self.js_axis.setChecked(True)
        self.js_axis.setObjectName(_fromUtf8("js_axis"))
        self.verticalLayout_4.addWidget(self.js_axis)
        self.js_accel = QtGui.QCheckBox(self.wizardPage)
        self.js_accel.setChecked(True)
        self.js_accel.setObjectName(_fromUtf8("js_accel"))
        self.verticalLayout_4.addWidget(self.js_accel)
        self.js_accon = QtGui.QCheckBox(self.wizardPage)
        self.js_accon.setObjectName(_fromUtf8("js_accon"))
        self.verticalLayout_4.addWidget(self.js_accon)
        self.js_speed = QtGui.QCheckBox(self.wizardPage)
        self.js_speed.setObjectName(_fromUtf8("js_speed"))
        self.verticalLayout_4.addWidget(self.js_speed)
        self.js_pos = QtGui.QCheckBox(self.wizardPage)
        self.js_pos.setObjectName(_fromUtf8("js_pos"))
        self.verticalLayout_4.addWidget(self.js_pos)
        NewDevW.addPage(self.wizardPage)
        self.wizardPage_2 = QtGui.QWizardPage()
        self.wizardPage_2.setObjectName(_fromUtf8("wizardPage_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.wizardPage_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.wizardPage_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.co_input = QtGui.QComboBox(self.wizardPage_2)
        self.co_input.setObjectName(_fromUtf8("co_input"))
        self.co_input.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.co_input)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.ch_lr3 = QtGui.QCheckBox(self.wizardPage_2)
        self.ch_lr3.setEnabled(True)
        self.ch_lr3.setObjectName(_fromUtf8("ch_lr3"))
        self.verticalLayout_5.addWidget(self.ch_lr3)
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.l_preview = QtGui.QLabel(self.groupBox_2)
        self.l_preview.setText(_fromUtf8(""))
        self.l_preview.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../usr/share/qtsixa/pics/(None).png")))
        self.l_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.l_preview.setObjectName(_fromUtf8("l_preview"))
        self.verticalLayout_3.addWidget(self.l_preview)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.warn_disablejoy_ico = QtGui.QLabel(self.wizardPage_2)
        self.warn_disablejoy_ico.setMaximumSize(QtCore.QSize(22, 22))
        self.warn_disablejoy_ico.setText(_fromUtf8(""))
        self.warn_disablejoy_ico.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/hint.png")))
        self.warn_disablejoy_ico.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.warn_disablejoy_ico.setObjectName(_fromUtf8("warn_disablejoy_ico"))
        self.horizontalLayout_7.addWidget(self.warn_disablejoy_ico)
        self.warn_disablejoy_txt = QtGui.QLabel(self.wizardPage_2)
        self.warn_disablejoy_txt.setObjectName(_fromUtf8("warn_disablejoy_txt"))
        self.horizontalLayout_7.addWidget(self.warn_disablejoy_txt)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        NewDevW.addPage(self.wizardPage_2)
        self.wizardPage_3 = QtGui.QWizardPage()
        self.wizardPage_3.setObjectName(_fromUtf8("wizardPage_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.wizardPage_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(self.wizardPage_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        NewDevW.addPage(self.wizardPage_3)

        self.retranslateUi(NewDevW)
        QtCore.QObject.connect(self.r_manual_led, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.r_led_n.setEnabled)
        QtCore.QObject.connect(self.ch_timeout, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.r_timeout.setEnabled)
        QtCore.QObject.connect(self.ch_rumble, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox.setEnabled)
        QtCore.QObject.connect(self.ch_led, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_3.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(NewDevW)

    def retranslateUi(self, NewDevW):
        NewDevW.setWindowTitle(_translate("NewDevW", "Wizard", None))
        self.wizardPage1.setTitle(_translate("NewDevW", "QtSixA", None))
        self.wizardPage1.setSubTitle(_translate("NewDevW", "Configure New Device", None))
        self.label_2.setText(_translate("NewDevW", "Let\'s Configure our device.\n"
"\n"
"First, select one at the combo-box bellow:", None))
        self.label.setText(_translate("NewDevW", "Configure this device:", None))
        self.co_dev.setItemText(0, _translate("NewDevW", "default", None))
        self.co_dev.setItemText(1, _translate("NewDevW", "hidraw", None))
        self.wizardPage2.setTitle(_translate("NewDevW", "QtSixA", None))
        self.wizardPage2.setSubTitle(_translate("NewDevW", "Select input types", None))
        self.ch_led.setText(_translate("NewDevW", "Enable &LEDs", None))
        self.ch_js.setText(_translate("NewDevW", "Enable &Joystick", None))
        self.ch_input.setText(_translate("NewDevW", "Enable &Input (Mouse/Keyboard)", None))
        self.ch_rumble.setText(_translate("NewDevW", "Enable Rumble", None))
        self.groupBox_3.setTitle(_translate("NewDevW", "LED #", None))
        self.r_auto_led.setText(_translate("NewDevW", "Auto select", None))
        self.ch_led_anim.setText(_translate("NewDevW", "Animate on new connection (LED/Rumble)", None))
        self.r_manual_led.setText(_translate("NewDevW", "Manual:", None))
        self.groupBox.setTitle(_translate("NewDevW", "Rumble Mode", None))
        self.r_rumble_new.setText(_translate("NewDevW", "New Mode", None))
        self.r_rumble_old.setText(_translate("NewDevW", "Old Mode", None))
        self.label_9.setText(_translate("NewDevW", "<i>This is the standard rumble mode.<br>It should work on most cases.</i>", None))
        self.label_8.setText(_translate("NewDevW", "<i>Select this only if you\'re going to play old games.<br>A known game that requires this mode is pSX.</i>", None))
        self.ch_timeout.setText(_translate("NewDevW", "Auto-disconnect device when unused for:", None))
        self.r_timeout.setSuffix(_translate("NewDevW", " mins", None))
        self.wizardPage.setTitle(_translate("NewDevW", "QtSixA", None))
        self.wizardPage.setSubTitle(_translate("NewDevW", "Configure Joystick", None))
        self.js_button.setText(_translate("NewDevW", "Enable &Buttons", None))
        self.js_sbutton.setText(_translate("NewDevW", "Enable &Sensible Buttons", None))
        self.js_axis.setText(_translate("NewDevW", "Enable &Axis", None))
        self.js_accel.setText(_translate("NewDevW", "Enable A&ccelerometers", None))
        self.js_accon.setText(_translate("NewDevW", "Enable Accelera&tion", None))
        self.js_speed.setText(_translate("NewDevW", "Enable Sp&eed", None))
        self.js_pos.setText(_translate("NewDevW", "Enable &Position", None))
        self.wizardPage_2.setTitle(_translate("NewDevW", "QtSixA", None))
        self.wizardPage_2.setSubTitle(_translate("NewDevW", "Configure Input", None))
        self.label_4.setText(_translate("NewDevW", "Use this Input Profile:", None))
        self.co_input.setItemText(0, _translate("NewDevW", "(None)", None))
        self.ch_lr3.setText(_translate("NewDevW", "Use L3/R3 to enable|disable axis/buttons", None))
        self.groupBox_2.setTitle(_translate("NewDevW", "Preview:", None))
        self.warn_disablejoy_txt.setText(_translate("NewDevW", "It\'s recommended that you disable \'Joystick\' mode when using this Input Profile.", None))
        self.wizardPage_3.setTitle(_translate("NewDevW", "QtSixA", None))
        self.wizardPage_3.setSubTitle(_translate("NewDevW", "Finished", None))
        self.label_6.setText(_translate("NewDevW", "Click on \'Finish\' to close this wizard", None))

import qtsixa_rc
